theme: minima
title: Portfolio
description: 
show_excerpts: true
plugins:
  - jekyll-feed

header_pages:
  - index.md

include:
  - index.md

defaults:
  - scope:
      path: "index.md"
    values:
      permalink: /index/

